import { PhaseConfig } from "../../types";

export const expertConfig: PhaseConfig = {
  id: "expert",
  name: "Expert",
  badge: "🚀 Production Scale (বিলিয়ন স্কেল)",
  tagline: "ডিস্ট্রিবিউটেড আইডি জেনারেটর, ডিবি রেপ্লিকেশন ও অ্যাসিনক্রোনাস অ্যানালিটিক্স পাইপলাইন",
  componentCount: 12,
  conceptSummary:
    "বিলিয়ন বিলিয়ন ইউআরএল এবং প্রতি সেকেন্ডে লক্ষ লক্ষ ক্লিক হ্যান্ডেল করার জন্য বিশ্বমানের এন্টারপ্রাইজ আর্কিটেকচার। এখানে ডিস্ট্রিবিউটেড আইডি জেনারেটর (Twitter Snowflake), রিড-রাইট আলাদা করতে Primary ও Read Replicas ডাটাবেজ, এবং ইউজারের স্পিড না কমিয়ে ব্যাকগ্রাউন্ডে ক্লিক গোনার জন্য Kafka কিউ ব্যবহার করা হয়।",
  keyConcepts: [
    "Distributed Unique ID Generation (Twitter Snowflake)",
    "Database Replication (Master-Slave / Primary-Replica)",
    "Asynchronous Event-Driven Analytics (Apache Kafka)",
    "API Gateway Pattern (Routing, Auth, Telemetry)",
    "High Availability & Zero Downtime Failover",
  ],
  nodes: [
    {
      id: "node-client",
      type: "simulationNode",
      position: { x: 40, y: 290 },
      data: {
        label: "Global Clients",
        subLabel: "Mobile, Web, APIs",
        category: "client",
        emoji: "📱",
        analogy: "সারা পৃথিবীর কোটি কোটি মানুষ।",
        description: "বিশ্বের যেকোনো প্রান্ত থেকে আসা রিকোয়েস্ট।",
        techSpecs: "Anycast / HTTP/3",
      },
    },
    {
      id: "node-cdn",
      type: "simulationNode",
      position: { x: 310, y: 100 },
      data: {
        label: "Cloudflare CDN",
        subLabel: "Edge Network (200+ PoPs)",
        category: "network",
        emoji: "🌐",
        analogy: "প্রতিটি শহরে ছোট ছোট ডেলিভারি হাব — যাতে প্রধান অফিসে না গিয়ে পাশের হাব থেকেই উত্তর পাওয়া যায়।",
        description: "ব্যবহারকারীর নিকটতম লোকেশন থেকে স্ট্যাটিক পেজ ও ক্যাশড রিডাইরেক্ট করে।",
        techSpecs: "Edge Cache / GeoDNS",
      },
    },
    {
      id: "node-lb",
      type: "simulationNode",
      position: { x: 310, y: 290 },
      data: {
        label: "Global Load Balancer",
        subLabel: "AWS ALB / Cloud LB",
        category: "network",
        emoji: "⚖️",
        analogy: "আন্তর্জাতিক এয়ারপোর্টের আধুনিক ট্রাফিক কন্ট্রোল টাওয়ার।",
        description: "ট্রাফিক হেলথ ও রিজিয়ন অনুযায়ী নিখুঁতভাবে রাউট করে।",
        techSpecs: "Layer 7 / SSL Offloading",
      },
    },
    {
      id: "node-gw",
      type: "simulationNode",
      position: { x: 580, y: 290 },
      data: {
        label: "API Gateway",
        subLabel: "Kong / Envoy Gateway",
        category: "security",
        emoji: "🚪",
        analogy: "বিশাল ভবনের সেন্ট্রাল রিসেপশন — যেখানে নিরাপত্তা তল্লাশি, আইডি কার্ড চেক এবং ভেতরে যাওয়ার পাস দেওয়া হয়।",
        description: "অথেন্টিকেশন, সিকিউরিটি ফিল্টারিং, রেট লিমিট ও মেট্রিক্স ম্যানেজ করে।",
        techSpecs: "JWT Auth / Circuit Breaker",
      },
    },
    {
      id: "node-idgen",
      type: "simulationNode",
      position: { x: 580, y: 90 },
      data: {
        label: "Snowflake ID Gen",
        subLabel: "64-bit Distributed Unique ID",
        category: "compute",
        emoji: "🏷️",
        analogy: "অদ্বিতীয় টোকেন মেকার মেশিন — যা সেকেন্ডে লাখ লাখ টোকেন বানালেও কখনো দুটি টোকেনের নাম্বার এক হবে না!",
        description: "টাইমস্ট্যাম্প + মেশিন আইডি দিয়ে 64-বিট ইউনিক ইন্টিজার বানায়। ডাটাবেজ লক দরকার হয় না।",
        techSpecs: "Snowflake / 10k IDs/ms",
      },
    },
    {
      id: "node-server-1",
      type: "simulationNode",
      position: { x: 860, y: 190 },
      data: {
        label: "App Cluster (S1)",
        subLabel: "Kubernetes Pod 1",
        category: "compute",
        emoji: "🖥️",
        analogy: "অফিসের এক্সপার্ট ইঞ্জিনিয়ার ১।",
        description: "অটো-স্কেলিং মাইক্রোসার্ভিস পড।",
        techSpecs: "Golang / gRPC",
      },
    },
    {
      id: "node-server-2",
      type: "simulationNode",
      position: { x: 860, y: 360 },
      data: {
        label: "App Cluster (S2)",
        subLabel: "Kubernetes Pod 2",
        category: "compute",
        emoji: "🖥️",
        analogy: "অফিসের এক্সপার্ট ইঞ্জিনিয়ার ২।",
        description: "লোড বাড়লে আপনাআপনি নতুন পড চালু হয়।",
        techSpecs: "K8s Auto-scaled",
      },
    },
    {
      id: "node-cache",
      type: "simulationNode",
      position: { x: 1140, y: 80 },
      data: {
        label: "Redis Cluster",
        subLabel: "Multi-Node Sharded Cache",
        category: "storage",
        emoji: "⚡",
        analogy: "সুপারফাস্ট মেমোরি যা ডেটা হারিয়ে গেলে অন্য ব্যাকআপ নোড থেকে পলকে রিকভার করে।",
        description: "মাল্টি-রিজিওন রেপ্লিকেটেড ক্যাশ।",
        techSpecs: "Cluster Mode / < 1ms",
      },
    },
    {
      id: "node-primary-db",
      type: "simulationNode",
      position: { x: 1140, y: 240 },
      data: {
        label: "Primary DB (Write)",
        subLabel: "PostgreSQL Master (ACID)",
        category: "storage",
        emoji: "📦",
        analogy: "মূল হেড অফিসের প্রধান ডায়েরি — যেখানে শুধু নতুন লিংকগুলো লেখা (Write) হয়।",
        description: "সকল রাইট (Write) অপারেশন এখানে সম্পন্ন হয়।",
        techSpecs: "Master / WAL Replication",
      },
    },
    {
      id: "node-replica-db",
      type: "simulationNode",
      position: { x: 1140, y: 400 },
      data: {
        label: "Read Replicas",
        subLabel: "PostgreSQL Slaves (Read-Only)",
        category: "storage",
        emoji: "📚",
        analogy: "মূল ডায়েরির একাধিক অবিকল কপি — যেখান থেকে কোটি কোটি মানুষ একসাথে লিংক পড়তে পারে!",
        description: "রিড কুয়েরি হ্যান্ডেল করে যাতে প্রাইমারি ডাটাবেজের ওপর কোনো চাপ না পড়ে।",
        techSpecs: "Async Replicated / Read-Pool",
      },
    },
    {
      id: "node-queue",
      type: "simulationNode",
      position: { x: 860, y: 520 },
      data: {
        label: "Kafka Queue",
        subLabel: "Distributed Event Stream",
        category: "queue",
        emoji: "📨",
        analogy: "চিঠির পোস্টবক্স — ইউজারকে রিডাইরেক্ট করে দিয়ে এই বক্সে একটি নোট ফেলে রাখা হয়: 'এই লিংকে অমুক দেশ থেকে একটা ক্লিক হয়েছে!'",
        description: "অ্যানালিটিক্স ইভেন্ট বাফার করে রাখে। কোনো রিকোয়েস্ট নষ্ট হয় না।",
        techSpecs: "Partitions / 100k events/s",
      },
    },
    {
      id: "node-worker",
      type: "simulationNode",
      position: { x: 1140, y: 520 },
      data: {
        label: "Analytics Engine",
        subLabel: "ClickHouse + Workers",
        category: "analytics",
        emoji: "📊",
        analogy: "ডাটা সায়েন্টিস্ট দল — যারা পোস্টবক্স থেকে চিঠি নিয়ে সুন্দর গ্রাফ ও ক্লিক কাউন্টার তৈরি করে।",
        description: "ব্যাকগ্রাউন্ডে ক্লিক কাউন্ট, দেশ, ব্রাউজার অ্যানালিটিক্স প্রসেস ও স্টোর করে।",
        techSpecs: "Columnar DB / Real-time OLAP",
      },
    },
  ],
  edges: [
    {
      id: "edge-client-to-lb",
      type: "animatedFlowEdge",
      source: "node-client",
      target: "node-lb",
      data: {
        label: "1. Global Ingress",
        particleColor: "#06b6d4",
      },
    },
    {
      id: "edge-lb-to-gw",
      type: "animatedFlowEdge",
      source: "node-lb",
      target: "node-gw",
      data: {
        label: "2. Gateway Ingress",
        particleColor: "#06b6d4",
      },
    },
    {
      id: "edge-gw-to-s1",
      type: "animatedFlowEdge",
      source: "node-gw",
      target: "node-server-1",
      data: {
        label: "3. Authenticated Route",
        particleColor: "#06b6d4",
      },
    },
    {
      id: "edge-s1-to-idgen",
      type: "animatedFlowEdge",
      source: "node-server-1",
      target: "node-idgen",
      data: {
        label: "4a. Fetch Snowflake ID",
        particleColor: "#eab308",
      },
    },
    {
      id: "edge-s1-to-primary",
      type: "animatedFlowEdge",
      source: "node-server-1",
      target: "node-primary-db",
      data: {
        label: "5a. Write to Master",
        particleColor: "#3b82f6",
      },
    },
    {
      id: "edge-s1-to-cache",
      type: "animatedFlowEdge",
      source: "node-server-1",
      target: "node-cache",
      data: {
        label: "5b. Populate Cache",
        particleColor: "#a855f7",
      },
    },
    {
      id: "edge-primary-to-replica",
      type: "animatedFlowEdge",
      source: "node-primary-db",
      target: "node-replica-db",
      data: {
        label: "Replicate WAL stream",
        particleColor: "#64748b",
      },
    },
    {
      id: "edge-s1-to-replica",
      type: "animatedFlowEdge",
      source: "node-server-1",
      target: "node-replica-db",
      data: {
        label: "Read Query (Fallback)",
        particleColor: "#10b981",
      },
    },
    {
      id: "edge-s1-to-queue",
      type: "animatedFlowEdge",
      source: "node-server-1",
      target: "node-queue",
      data: {
        label: "Async Publish: click_event",
        particleColor: "#ec4899",
      },
    },
    {
      id: "edge-queue-to-worker",
      type: "animatedFlowEdge",
      source: "node-queue",
      target: "node-worker",
      data: {
        label: "Batch Consume & Aggregate",
        particleColor: "#f43f5e",
      },
    },
  ],
  flows: {
    shorten: [
      {
        id: "e-s1",
        flowType: "shorten",
        stepNumber: 1,
        title: "Client Request through Global LB & API Gateway (গেটওয়ে যাচাইকরণ)",
        whatHappens:
          "ক্লায়েন্টের রিকোয়েস্ট লোড ব্যালেন্সার হয়ে API Gateway-তে আসলো। গেটওয়ে ইউজারের API কী এবং রেট লিমিট ভেরিফাই করে অ্যাপ সার্ভার ক্লাস্টারে পাঠালো।",
        whyItMatters:
          "সেন্ট্রালাইজড অথেন্টিকেশন, SSL টার্মিনেশন এবং ট্রাফিক ফিল্টারিং ব্যাকএন্ড মাইক্রোসার্ভিসগুলোকে সুরক্ষিত রাখে।",
        analogy: "🏢 সিকিউরিটি চেকপয়েন্ট পার হয়ে বিশেষ পাস নিয়ে মূল ভবনে প্রবেশ।",
        activeNodeIds: ["node-client", "node-lb", "node-gw", "node-server-1"],
        activeEdgeIds: ["edge-client-to-lb", "edge-lb-to-gw", "edge-gw-to-s1"],
        nodeStatusMessages: {
          "node-client": "POST /api/v2/shorten",
          "node-gw": "JWT Validated | Rate: OK",
          "node-server-1": "Request assigned to Pod-1",
        },
        payloadSnippet: `POST /api/v2/shorten HTTP/2\nAuthorization: Bearer eyJhbGciOi...\nX-Request-Id: req_9fa8120c`,
      },
      {
        id: "e-s2",
        flowType: "shorten",
        stepNumber: 2,
        title: "Distributed Snowflake ID Generation (ইউনিক আইডি তৈরি)",
        whatHappens:
          "সার্ভার ডাটাবেজে লক না লাগিয়ে আলাদা 'Snowflake ID Generator' সার্ভিসের কাছ থেকে একটি ইউনিক 64-বিট নাম্বার (যেমন: 154892019482) নিয়ে নিলো এবং সেটাকে Base62 কোডে (যেমন: '9wK2pL') রূপান্তর করলো।",
        whyItMatters:
          "ডাটাবেজ অটো-ইনক্রিমেন্ট আইডি ব্যবহার করলে মাল্টি-ডাটাবেজ সিস্টেমে কলিশন বা বটলনেক তৈরি হয়। Snowflake পদ্ধতিতে স্বাধীনভাবে সেকেন্ডে লাখ লাখ আইডি জেনারেট হয়।",
        analogy: "🏷️ সেন্ট্রাল কিউ ছাড়াই প্রতিটি মেশিন নিজের স্বতন্ত্র ডিজিটাল বারকোড প্রিন্ট করে নেওয়া।",
        activeNodeIds: ["node-server-1", "node-idgen"],
        activeEdgeIds: ["edge-s1-to-idgen"],
        nodeStatusMessages: {
          "node-idgen": "Snowflake ID: 154892019482390144",
          "node-server-1": "Base62 Encoded -> '9wK2pL'",
        },
        payloadSnippet: `// Twitter Snowflake 64-bit structure:\n// 1 bit unused | 41 bit timestamp | 10 bit machine ID | 12 bit sequence\nconst id = snowflake.nextId(); // 154892019482390144\nconst shortCode = base62Encode(id); // "9wK2pL"`,
      },
      {
        id: "e-s3",
        flowType: "shorten",
        stepNumber: 3,
        title: "Write to Primary DB & Replicate to Read Replicas (মাস্টারে সেভ ও রেপ্লিকেশন)",
        whatHappens:
          "সার্ভার ডাটাবেজ মাস্টারে লিংকটি সেভ করলো। প্রাইমারি ডাটাবেজ ব্যাকগ্রাউন্ডে সাথে সাথে সব রিড-রেপ্লিকা (কপি) ডাটাবেজে সেই তথ্য ছড়িয়ে দিলো।",
        whyItMatters:
          "Write গুলো শুধু Primary তে যায়, কিন্তু কোটি কোটি Read কোয়েরিগুলো হ্যান্ডেল করার জন্য রিড-রেপ্লিকাগুলো প্রস্তুত থাকে (CQRS প্যাটার্ন)।",
        analogy: "✍️ মূল খাতায় লেখার সাথে সাথে সব ফটোকপি মেশিনে নতুন পৃষ্ঠার কপি তৈরি হয়ে যাওয়া।",
        activeNodeIds: ["node-server-1", "node-primary-db", "node-replica-db", "node-cache"],
        activeEdgeIds: ["edge-s1-to-primary", "edge-primary-to-replica", "edge-s1-to-cache"],
        nodeStatusMessages: {
          "node-primary-db": "MASTER WRITE SUCCESS",
          "node-replica-db": "WAL Stream Syncing (Lag: 0.2ms)",
          "node-cache": "Redis Key Cached with TTL",
        },
        payloadSnippet: `BEGIN TRANSACTION;\nINSERT INTO urls_sharded_04 (id, short_code, original_url, user_id)\nVALUES (154892019482390144, '9wK2pL', 'https://...', 9012);\nCOMMIT;`,
      },
      {
        id: "e-s4",
        flowType: "shorten",
        stepNumber: 4,
        title: "Instant Response to User (ইউজারকে রেসপন্স পাঠানো)",
        whatHappens:
          "ইউজার মাত্র ৮ মিলিসেকেন্ডে তার ব্র্যান্ডেড শর্ট লিঙ্ক (https://link.co/9wK2pL) পেয়ে গেলো।",
        whyItMatters:
          "ডিস্ট্রিবিউটেড ইনফ্রাস্ট্রাকচারের অপ্টিমাইজেশনের ফলে ৯৯.৯৯% রিকোয়েস্ট লেটেন্সি সাব-১০ মিলিসেকেন্ডের নিচে থাকে।",
        analogy: "✨ পলকের মধ্যে কাজ শেষ হওয়া।",
        activeNodeIds: ["node-server-1", "node-gw", "node-client"],
        activeEdgeIds: ["edge-gw-to-s1", "edge-lb-to-gw", "edge-client-to-lb"],
        nodeStatusMessages: {
          "node-server-1": "HTTP 201 Created",
          "node-client": "Created: https://link.co/9wK2pL",
        },
        payloadSnippet: `{\n  "success": true,\n  "shortUrl": "https://link.co/9wK2pL",\n  "id": "154892019482390144",\n  "latencyMs": 7.8\n}`,
      },
    ],
    redirect: [
      {
        id: "e-r1",
        flowType: "redirect",
        stepNumber: 1,
        title: "Global Ingress & Redis Cluster Lookup (ক্যাশ থেকে পলকে সন্ধান)",
        whatHappens:
          "একজন ইউজার শর্ট লিংকে ক্লিক করলেন। রিকোয়েস্ট গেটওয়ে হয়ে অ্যাপ সার্ভার ১-এ পৌঁছামাত্র সার্ভার ডিস্ট্রিবিউটেড Redis ক্লাস্টার চেক করলো এবং ০.৫ মিলিসেকেন্ডেই লিংকটি পেয়ে গেলো!",
        whyItMatters:
          "মাল্টি-নোড Redis ক্লাস্টারে ডেটা শার্ডিং থাকায় লাখ লাখ কনকারেন্ট রিড রিকোয়েস্ট ডাটাবেজে না গিয়েই মেমোরি থেকে সমাধান হয়।",
        analogy: "⚡ সুপার কম্পিউটারের মেমোরি থেকে ১ সেকেন্ডের হাজার ভাগের এক ভাগে তথ্য বের করা।",
        activeNodeIds: ["node-client", "node-gw", "node-server-1", "node-cache"],
        activeEdgeIds: ["edge-client-to-lb", "edge-gw-to-s1", "edge-s1-to-cache"],
        nodeStatusMessages: {
          "node-client": "GET /9wK2pL",
          "node-cache": "SHARD_02: CACHE HIT (0.4ms)",
          "node-server-1": "Found target URL!",
        },
        payloadSnippet: `REDIS_CLUSTER.GET("{url}:9wK2pL")\n=> "https://systemdesign.com/expert-deep-dive"\nLatency: 0.4ms`,
      },
      {
        id: "e-r2",
        flowType: "redirect",
        stepNumber: 2,
        title: "Asynchronous Kafka Event Publish (অ্যাসিনক্রোনাস অ্যানালিটিক্স ইভেন্ট)",
        whatHappens:
          "ইউজারকে অপেক্ষা না করিয়ে সাথে সাথে আসল ঠিকানায় রিডাইরেক্ট করে দেওয়া হলো, এবং ব্যাকগ্রাউন্ডে Kafka কিউতে একটি বার্তা ছুড়ে দেওয়া হলো: 'এই লিংকে ১টি ক্লিক হয়েছে, ব্রাউজার: Chrome, দেশ: বাংলাদেশ'!",
        whyItMatters:
          "ইউজার কোনো ল্যাগ অনুভব করে না (Non-blocking I/O)। অ্যানালিটিক্স ব্যাকগ্রাউন্ডে প্রসেস হওয়ায় রিডাইরেক্ট স্পিড সর্বোচ্চ থাকে।",
        analogy: "📨 চিঠি পোস্টবক্সে ফেলে দিয়ে সাথে সাথে নিজের গন্তব্যে রওনা হওয়া — পোস্টম্যান পরে চিঠি ডেলিভারি করবে।",
        activeNodeIds: ["node-server-1", "node-client", "node-queue"],
        activeEdgeIds: ["edge-s1-to-queue", "edge-client-to-lb"],
        nodeStatusMessages: {
          "node-server-1": "301 Redirect sent to client!",
          "node-client": "Redirecting instantly (3.1ms)...",
          "node-queue": "Kafka Topic: 'url-clicks' received event",
        },
        payloadSnippet: `// 1. Immediate redirect\nres.redirect(301, targetUrl);\n\n// 2. Fire-and-forget Kafka event\nkafkaProducer.send({\n  topic: 'url-clicks',\n  messages: [{ key: '9wK2pL', value: JSON.stringify({ ts: Date.now(), ip: '...', country: 'BD' }) }]\n});`,
      },
      {
        id: "e-r3",
        flowType: "redirect",
        stepNumber: 3,
        title: "Analytics Worker processes click in ClickHouse DB (অ্যানালিটিক্স সংরক্ষণ)",
        whatHappens:
          "Kafka থেকে অ্যানালিটিক্স ওয়ার্কার মেসেজটি তুলে নিয়ে ClickHouse টাইম-সিরিজ ডাটাবেজে স্টোর করলো। ফলে অ্যাডমিন ড্যাশবোর্ডে রিয়েল-টাইম গ্রাফ আপডেট হয়ে গেলো!",
        whyItMatters:
          "কলামনার ডাটাবেজ (ClickHouse) প্রতি সেকেন্ডে লক্ষ লক্ষ ক্লিক ইভেন্ট এগ্রিগেট করতে পারে এবং সাব-সেকেন্ডে অ্যানালিটিক্স কুয়েরির উত্তর দেয়।",
        analogy: "📊 অফিসের পেছনের রুমে বসে হিসাবরক্ষকের খাতায় সুন্দর করে পাই-চার্ট আঁকা।",
        activeNodeIds: ["node-queue", "node-worker"],
        activeEdgeIds: ["edge-queue-to-worker"],
        nodeStatusMessages: {
          "node-queue": "Delivered to consumer group",
          "node-worker": "ClickHouse INSERT +1 click (Total: 4,192,051)",
        },
        payloadSnippet: `INSERT INTO click_analytics (short_code, clicked_at, country, browser)\nVALUES ('9wK2pL', NOW(), 'BD', 'Chrome 128');`,
      },
    ],
  },
};
